default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  password:
  pool: 8

development:
  <<: *default
  database: pet-dev

test:
  <<: *default
  database: pet-test

production:
  <<: *default
  database: pet-prod
